#version 450

layout(set = 0, binding = 0, r8ui) uniform uimage2D valuesLhs;
layout(set = 0, binding = 1, r8ui) uniform uimage2D valuesRhs;
layout(set = 0, binding = 2, r8ui) uniform uimage2D imageOutput;
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    imageStore(imageOutput, ivec2(x, y), imageLoad(valuesLhs, ivec2(x,y)) + imageLoad(valuesRhs, ivec2(x,y)));
}